name: Docker Test Build

on:
  push:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
      
      - name: Build the tagged Docker image
        run: docker build . -t darmiel/todoist-project-allocation:${{steps.vars.outputs.tag}}