name: Docker Test Build

on:
  push:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the tagged Docker image
        run: docker build .